### ISSUE TITLE
NoClassDefFoundError on run time

### ISSUE THREAD

**Issue by gonsan** [vert-x/mod-mysql-postgresql#37]
I have this problem.. :(

this module was deployed well.

But, sometimes I have a follow problem on run time.

java.lang.NoClassDefFoundError: com/github/mauricio/async/db/util/ByteBufferUtils$
    at com.github.mauricio.async.db.mysql.codec.MySQLFrameDecoder.decode(MySQLFrameDecoder.scala:63)
    at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:241)
    at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:149)
    at io.netty.channel.DefaultChannelHandlerContext.invokeChannelRead(DefaultChannelHandlerContext.java:341)
    at io.netty.channel.DefaultChannelHandlerContext.fireChannelRead(DefaultChannelHandlerContext.java:327)
    at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:785)
    at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:126)
    at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:507)
    at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:464)
    at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:378)
    at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:350)
    at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:116)
    at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.ClassNotFoundException: com.github.mauricio.async.db.util.ByteBufferUtils$
    at org.vertx.java.platform.impl.ModuleClassLoader.loadFromModule(ModuleClassLoader.java:127)
    at org.vertx.java.platform.impl.ModuleClassLoader.loadClass(ModuleClassLoader.java:108)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
    ... 13 more

I'm using 
- Vert.x 2.1
- Ubuntu 14.0.4 (Windwos  is working well..)
- scala=io.vertx~lang-scala~1.0.0:org.vertx.scala.platform.impl.ScalaVerticleFactory

**Comment by adri0** [comment]
I also have it happening from time to time for apparently no reason. I noticed the error seems to happen more often when my application is under heavy load, and generally in the first seconds/minutes after the start. The warmup of the server seems to have some influence over it too. I'm not really sure. Indeed annoying.

**Comment by ekosystem** [comment]
I have the same problem. Deploying on my computer works fine, deploying on Jenkins produces:

```
java.lang.NoClassDefFoundError: com/github/mauricio/async/db/postgresql/messages/frontend/StartupMessage
        at com.github.mauricio.async.db.postgresql.codec.PostgreSQLConnectionHandler.channelActive(PostgreSQLConnectionHandler.scala:123)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelActive(AbstractChannelHandlerContext.java:208)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelActive(AbstractChannelHandlerContext.java:194)
        at io.netty.channel.ChannelInboundHandlerAdapter.channelActive(ChannelInboundHandlerAdapter.java:64)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelActive(AbstractChannelHandlerContext.java:208)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelActive(AbstractChannelHandlerContext.java:194)
        at io.netty.channel.DefaultChannelPipeline.fireChannelActive(DefaultChannelPipeline.java:758)
        at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.fulfillConnectPromise(AbstractNioChannel.java:259)
        at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.finishConnect(AbstractNioChannel.java:288)
        at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:528)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:468)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:382)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:354)
        at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:116)
        at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.ClassNotFoundException: com.github.mauricio.async.db.postgresql.messages.frontend.StartupMessage
        at org.vertx.java.platform.impl.ModuleClassLoader.loadFromModule(ModuleClassLoader.java:127)
        at org.vertx.java.platform.impl.ModuleClassLoader.loadClass(ModuleClassLoader.java:108)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        ... 15 more
```

any ideas?

**Comment by litch** [comment]
I never did make any progress on this - I found it easier to just leave an `async_db` module running in a separate vert.x instance in the cluster.  The best I could tell was that it was from it starting to handle messages before the classes were totally loaded.

**Comment by ekosystem** [comment]
I suppose so. When I add 2000ms delay after `async_db` module initialized but before other verticles initialization it started to work correctly.
I wonder if there is small bug here: https://github.com/vert-x/mod-mysql-postgresql/blob/master/src/main/scala/io/vertx/asyncsql/Starter.scala#L34

Handler is added without any wait until registration is confirmed. When there are few vertx instances in cluster registration can take some time. Maybe then other modules start to query not-totally loaded `async_db` module?

**Comment by litch** [comment]
That looks likely to me, though I have very little understandings of this project.

**Comment by Narigo** [comment]
@ekosystem I guess you are right here. Do you want to provide a pull request for this?

**Comment by Narigo** [comment]
@ekosystem can you try out the fix here?
https://github.com/vert-x/mod-mysql-postgresql/tree/wait-for-registered-handler
